pipeline {
    agent any
    
    tools {
        jdk 'JDK17'
        maven 'Maven3'
    }
    
    stages {
        stage('Checkout') {
            steps {
                echo 'Starting checkout...'
                checkout scm
                sh 'pwd'
                sh 'ls -la'
                echo 'Checkout complete'
            }
        }
        
        stage('Build') {
            steps {
                echo 'Starting build...'
                dir('student-management') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        
        stage('Test') {
            steps {
                echo 'Starting tests...'
                dir('student-management') {
                    sh 'mvn test -Dspring.profiles.active=test'
                }
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline finished'
        }
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!!'
        }
    }
}